version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ihs-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ihs_connect
      POSTGRES_USER: ihs_user
      POSTGRES_PASSWORD: ihs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ihs_user -d ihs_connect"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
    driver: local
